name: CasinoPlugin
author: chrisimi
main: com.chrisimi.casino.main.Main
version: 3.7
api-version: 1.13
softdepend: [Multiverse-Core, Ultimate_Economy, HolographicDisplays]
depend: [Vault]


commands:
  casino:
    description: shows the plugin info
    usage: /casino 
  casino gui:
    description: opens the casino GUI
    usage: /casino
    permission: casino.gui
  casino updateconfig:
    description: updates the config
    usage: /casino updateconfig
    permission: casino.admin
  casino reloadconfig:
    description: reloads the config
    usage: /casino reloadconfig
    permission: casino.admin
  casino help:
    description: get help for this plugin
    usage: /casino help
  casino admin: 
    description: get help as an admin for this plugin
    usage: /casino admin
    permission: casino.admin
  casino help slots:
    description: get the help for slots signs
    usage: /casion help slot
  casino help dice:
    description: get the help for dice signs
    usage: /casino help dice
  casino help blackjack:
    description: get help for blackjack signs
    usage: /casino help blackjack
  casino help leaderboard:
    description: get help for leaderboard signs
    usage: /casino help leaderboard
  casino sign enable:
    description: enable your playersign
    usage: /casino sign enable
    permission: [casino.dice.create, casino.blackjack.create]
  casino sign disable:
    description: disable your playersign
    usage: /casino sign disable
    permission: [casino.dice.create, casino.blackjack.create]
  casino roll:
    description: roll a random number
    usage: /casino roll [minimum] [maximum] [player (not needed)]
    permission: casino.roll
  casino createchest:
    description: create a new SlotChest while looking onto it
    usage: /casino createchest
    permission: casino.slotchest.create
  casino chestlocations:
    description: get the locations from all SlotChest you made
    usage: /casino chestlocations
    permission: casino.slotchest.create
  casino resetdata:
    description: reset the data file
    usage: /casino resetdata
    permission: casino.admin
  casino reloaddata:
    description: reload all datas and leaderboardsigns
    usage: /casino reloaddata
    permission: casino.admin
  casino resetleaderboard:
    description: reset leaderboard signs in range
    usage: /casino resetleaderboard
    permission: [casino.admin, casino.serversigns]
  casino resetserverleaderboard:
    description: reset serverleaderboard signs in range
    usage: /casino resetserverleaderboard
    permission: [casino.admin, casino.serversigns]
  casino reloadmessages:
    description: reload message-system
    usage: /casino reloadmessages
    permission: casino.admin
  casino resetsign:
    description: reset the sign when it bugs
    usage: /casino resetsign
    permission: casino.admin
  casino deletereset:
    description: deletes the manual reset from the sign 
    usage: /casino deletereset
    permission: [casino.admin, casino.leaderboard.create, casino.serversigns]
  casino setdate:
    description: set a date for a leaderboardsign
    usage: /casino setdate
    permission: [casino.admin, casino.leaderboard.create, casino.serversigns]
  casino edithologram:
    description: edit a created hologram
    usage: /casino edithologram <name>
    permission: [casino.admin, casino.hologram.create, casino.hologram.server]
  casino createhologram:
    description: create a hologram
    usage: /casino createhologram
    permission: [casino.admin, casino.hologram.create, casino.hologram.server]